version: '2'
services:
    discovery1-app:
        image: discovery1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://discovery1-mysql:3306/discovery1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    discovery1-mysql:
        extends:
            file: mysql.yml
            service: discovery1-mysql
